[pytest]

# Test discovery
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Output options
addopts =
    -v
    -s
    --disable-warnings
    --html=report.html
    --self-contained-html

# Parallel execution (pytest-xdist)
# You can override in Jenkins with -n 2 or -n auto
# addopts = -n auto

# Allure results directory
allure_report_dir = allure-results

# Logging
log_cli = true
log_cli_level = INFO